<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2e349be3-ba53-44ab-897f-52fc46b56c34</elementGuidId>
    <imagePath></imagePath>
    <name>select_shipping_address_country_id</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[7]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-shipping-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r8:') and equals(@name,'shipping_address.country_id') and equals(@class,'MuiNativeSelect-select MuiNativeSelect-standard MuiInputBase-input MuiInput-input css-1vynybe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiNativeSelect-select MuiNativeSelect-standard MuiInputBase-input MuiInput-input css-1vynybe</value>
        <webElementGuid>e7373bf4-3576-4fa6-ae53-63cd49f4edf4</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r8:</value>
        <webElementGuid>c7dbb5dc-3c6b-4b63-8933-4939eb24918e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.country_id</value>
        <webElementGuid>558c9a6c-2dd0-4db6-8beb-53c8dd4524c5</webElementGuid>
    </webElementProperties>
</WebElementEntity>