<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ca3a9968-6158-4629-9327-f1c0162dc0fc</elementGuidId>
    <imagePath></imagePath>
    <name>input_payment_method_id</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.bdl-payment-form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'payment_method_id') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>3e6a6365-4bbf-4eba-a816-1cc64671fb31</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>payment_method_id</value>
        <webElementGuid>d54e6e96-a964-44b1-81a3-d08f52a3af19</webElementGuid>
    </webElementProperties>
</WebElementEntity>